# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ditu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_map(object):
    def setupUi(self, map):
        map.setObjectName("map")
        map.resize(800, 800)

        self.retranslateUi(map)
        QtCore.QMetaObject.connectSlotsByName(map)

    def retranslateUi(self, map):
        _translate = QtCore.QCoreApplication.translate
        map.setWindowTitle(_translate("map", "地图"))
