# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fenbushi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fenbushi(object):
    def setupUi(self, fenbushi):
        fenbushi.setObjectName("fenbushi")
        fenbushi.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(fenbushi)
        self.centralwidget.setObjectName("centralwidget")
        self.fensbushi_num = QtWidgets.QLineEdit(self.centralwidget)
        self.fensbushi_num.setGeometry(QtCore.QRect(220, 30, 61, 20))
        self.fensbushi_num.setObjectName("fensbushi_num")
        self.ok_fenbushi = QtWidgets.QPushButton(self.centralwidget)
        self.ok_fenbushi.setGeometry(QtCore.QRect(690, 500, 75, 23))
        self.ok_fenbushi.setObjectName("ok_fenbushi")
        self.fenbushi_labal = QtWidgets.QLabel(self.centralwidget)
        self.fenbushi_labal.setGeometry(QtCore.QRect(30, 30, 171, 16))
        self.fenbushi_labal.setObjectName("fenbushi_labal")
        self.ok_fenbushinum = QtWidgets.QPushButton(self.centralwidget)
        self.ok_fenbushinum.setGeometry(QtCore.QRect(300, 30, 75, 23))
        self.ok_fenbushinum.setObjectName("ok_fenbushinum")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(50, 80, 710, 400))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 690, 600))
        self.scrollAreaWidgetContents.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scrollAreaWidgetContents.setAutoFillBackground(True)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.fensbushi_loc = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fensbushi_loc.setGeometry(QtCore.QRect(30, 10, 111, 16))
        self.fensbushi_loc.setObjectName("fensbushi_loc")
        self.fenbushi_loc2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fenbushi_loc2.setGeometry(QtCore.QRect(170, 10, 161, 16))
        self.fenbushi_loc2.setObjectName("fenbushi_loc2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        fenbushi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(fenbushi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuNew = QtWidgets.QMenu(self.menuFiles)
        self.menuNew.setObjectName("menuNew")
        fenbushi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(fenbushi)
        self.statusbar.setObjectName("statusbar")
        fenbushi.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(fenbushi)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(fenbushi)
        self.actionSave.setObjectName("actionSave")
        self.actionRobot_info = QtWidgets.QAction(fenbushi)
        self.actionRobot_info.setObjectName("actionRobot_info")
        self.actionFenbushi = QtWidgets.QAction(fenbushi)
        self.actionFenbushi.setObjectName("actionFenbushi")
        self.actionPlanwork = QtWidgets.QAction(fenbushi)
        self.actionPlanwork.setObjectName("actionPlanwork")
        self.menuNew.addAction(self.actionRobot_info)
        self.menuNew.addAction(self.actionFenbushi)
        self.menuNew.addAction(self.actionPlanwork)
        self.menuFiles.addAction(self.menuNew.menuAction())
        self.menuFiles.addAction(self.actionOpen)
        self.menuFiles.addAction(self.actionSave)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(fenbushi)
        QtCore.QMetaObject.connectSlotsByName(fenbushi)

    def retranslateUi(self, fenbushi):
        _translate = QtCore.QCoreApplication.translate
        fenbushi.setWindowTitle(_translate("fenbushi", "创能机器人配置软件"))
        self.ok_fenbushi.setText(_translate("fenbushi", "确认"))
        self.fenbushi_labal.setText(_translate("fenbushi", "请输入现场分布式传感器个数："))
        self.ok_fenbushinum.setText(_translate("fenbushi", "确认"))
        self.fensbushi_loc.setText(_translate("fenbushi", "分布式传感器位置"))
        self.fenbushi_loc2.setText(_translate("fenbushi", "分布式传感器对应点位置"))
        self.menuFiles.setTitle(_translate("fenbushi", "Files"))
        self.menuNew.setTitle(_translate("fenbushi", "New"))
        self.actionOpen.setText(_translate("fenbushi", "Open"))
        self.actionSave.setText(_translate("fenbushi", "Save"))
        self.actionRobot_info.setText(_translate("fenbushi", "Robot_info"))
        self.actionFenbushi.setText(_translate("fenbushi", "Fenbushi"))
        self.actionPlanwork.setText(_translate("fenbushi", "Planwork"))
