# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 60, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuNew = QtWidgets.QMenu(self.menuFiles)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRobot_info = QtWidgets.QAction(MainWindow)
        self.actionRobot_info.setObjectName("actionRobot_info")
        self.actionFenbushi = QtWidgets.QAction(MainWindow)
        self.actionFenbushi.setObjectName("actionFenbushi")
        self.actionPlanwork = QtWidgets.QAction(MainWindow)
        self.actionPlanwork.setObjectName("actionPlanwork")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.menuNew.addAction(self.actionRobot_info)
        self.menuNew.addAction(self.actionFenbushi)
        self.menuNew.addAction(self.actionPlanwork)
        self.menuFiles.addAction(self.menuNew.menuAction())
        self.menuFiles.addAction(self.actionopen)
        self.menuFiles.addAction(self.actionsave)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "创能机器人配置软件"))
        self.label.setText(_translate("MainWindow", "创能机器人配置软件"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.actionRobot_info.setText(_translate("MainWindow", "Robot_info"))
        self.actionFenbushi.setText(_translate("MainWindow", "Fenbushi"))
        self.actionPlanwork.setText(_translate("MainWindow", "Planwork"))
        self.actionopen.setText(_translate("MainWindow", "Open"))
        self.actionsave.setText(_translate("MainWindow", "Save"))
