# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.setEnabled(True)
        login.resize(401, 418)
        font = QtGui.QFont()
        font.setPointSize(12)
        login.setFont(font)
        self.lineEdit = QtWidgets.QLineEdit(login)
        self.lineEdit.setGeometry(QtCore.QRect(180, 150, 120, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(login)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 200, 120, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(100, 150, 60, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(100, 200, 60, 30))
        self.label_2.setObjectName("label_2")
        self.welcome = QtWidgets.QLabel(login)
        self.welcome.setGeometry(QtCore.QRect(100, 60, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.welcome.setFont(font)
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.pushButton = QtWidgets.QPushButton(login)
        self.pushButton.setGeometry(QtCore.QRect(90, 260, 80, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(login)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 260, 80, 30))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "登录"))
        self.lineEdit.setPlaceholderText(_translate("login", "请输入账号"))
        self.lineEdit_2.setPlaceholderText(_translate("login", "请输入密码"))
        self.label.setText(_translate("login", "账号："))
        self.label_2.setText(_translate("login", "密码："))
        self.welcome.setText(_translate("login", "WELCOME"))
        self.pushButton.setText(_translate("login", "登录"))
        self.pushButton_2.setText(_translate("login", "取消"))
