# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xunluoluxian.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_xunluoluxian(object):
    def setupUi(self, xunluoluxian):
        xunluoluxian.setObjectName("xunluoluxian")
        xunluoluxian.resize(530, 383)
        self.add_xllx = QtWidgets.QPushButton(xunluoluxian)
        self.add_xllx.setGeometry(QtCore.QRect(24, 20, 91, 23))
        self.add_xllx.setObjectName("add_xllx")
        self.scrollArea = QtWidgets.QScrollArea(xunluoluxian)
        self.scrollArea.setGeometry(QtCore.QRect(20, 50, 481, 291))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 289))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(20, 10, 80, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(120, 10, 320, 20))
        self.label_2.setObjectName("label_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.ok_addxllx = QtWidgets.QPushButton(xunluoluxian)
        self.ok_addxllx.setGeometry(QtCore.QRect(340, 350, 75, 23))
        self.ok_addxllx.setObjectName("ok_addxllx")
        self.re_addxllx = QtWidgets.QPushButton(xunluoluxian)
        self.re_addxllx.setGeometry(QtCore.QRect(430, 350, 75, 23))
        self.re_addxllx.setObjectName("re_addxllx")

        self.retranslateUi(xunluoluxian)
        QtCore.QMetaObject.connectSlotsByName(xunluoluxian)

    def retranslateUi(self, xunluoluxian):
        _translate = QtCore.QCoreApplication.translate
        xunluoluxian.setWindowTitle(_translate("xunluoluxian", "巡逻路线"))
        self.add_xllx.setText(_translate("xunluoluxian", "添加巡逻路线"))
        self.label.setText(_translate("xunluoluxian", "路线名称"))
        self.label_2.setText(_translate("xunluoluxian", "巡逻点"))
        self.ok_addxllx.setText(_translate("xunluoluxian", "确定"))
        self.re_addxllx.setText(_translate("xunluoluxian", "返回"))
